### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by balsoft** [corngood/portable-nixos-container#1]
Hi!

I've managed to use this project to set up nixos-container on Debian, and would like to contribute some improvements. However, to do so I'd like to know the license of this project. If you need help with deciding on one, here are some good open-source licenses: https://choosealicense.com/licenses/

**Comment by corngood** [comment]
Hi,

I added the MIT licence.  I'm happy to take updates, but I always sort of planned on getting this into nixpkgs at some point.  I'm just not sure what form that would take.

**Comment by balsoft** [comment]
Thank you!
